/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erayn
 */
public class tas_kagit_makas extends javax.swing.JFrame {

    /**
     * Creates new form tas_kagit_makas
     */
    public tas_kagit_makas() {
        initComponents();
        jpanel_oyun_alani.setVisible(false);
        jpanel_skor_alani.setVisible(false);
    }
    String ad = ""; int oyuncuskor = 0, bilgisayarskor = 0, oyuncu = 0 , bilgisayar = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_kayit_alani = new javax.swing.JPanel();
        jlabel_oyuncu_adi = new javax.swing.JLabel();
        textfield_oyuncu_adi = new javax.swing.JTextField();
        button_basla = new javax.swing.JButton();
        jpanel_skor_alani = new javax.swing.JPanel();
        label_oyuncu = new javax.swing.JLabel();
        label_bilgisayar = new javax.swing.JLabel();
        button_yeni_oyun = new javax.swing.JButton();
        label_oyuncu_skor = new javax.swing.JLabel();
        label_bilgisayar_skor = new javax.swing.JLabel();
        jpanel_oyun_alani = new javax.swing.JPanel();
        button_resim_oyuncu = new javax.swing.JButton();
        button_resim_bilgisayar = new javax.swing.JButton();
        button_oyna = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combobox_oyuncu = new javax.swing.JComboBox<>();
        combobox_bilgisayar = new javax.swing.JComboBox<>();
        jlabel_durum = new javax.swing.JLabel();
        jlabel_kazanan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel_kayit_alani.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oyuncu Bilgileri", null, null, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jlabel_oyuncu_adi.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jlabel_oyuncu_adi.setText("Oyuncu Adı:");

        textfield_oyuncu_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_oyuncu_adiActionPerformed(evt);
            }
        });

        button_basla.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        button_basla.setText("Başla");
        button_basla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_baslaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_kayit_alaniLayout = new javax.swing.GroupLayout(jpanel_kayit_alani);
        jpanel_kayit_alani.setLayout(jpanel_kayit_alaniLayout);
        jpanel_kayit_alaniLayout.setHorizontalGroup(
            jpanel_kayit_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_kayit_alaniLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpanel_kayit_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanel_kayit_alaniLayout.createSequentialGroup()
                        .addComponent(button_basla)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanel_kayit_alaniLayout.createSequentialGroup()
                        .addComponent(jlabel_oyuncu_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_oyuncu_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        jpanel_kayit_alaniLayout.setVerticalGroup(
            jpanel_kayit_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_kayit_alaniLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanel_kayit_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel_oyuncu_adi)
                    .addComponent(textfield_oyuncu_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(button_basla)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jpanel_skor_alani.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Skorlar\n", null, null, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        label_oyuncu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        label_oyuncu.setText("Oyuncu :");

        label_bilgisayar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        label_bilgisayar.setText("Bilgisayar :");

        button_yeni_oyun.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        button_yeni_oyun.setText("Yeni Oyun");
        button_yeni_oyun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_yeni_oyunActionPerformed(evt);
            }
        });

        label_oyuncu_skor.setText("0");

        label_bilgisayar_skor.setText("0");

        javax.swing.GroupLayout jpanel_skor_alaniLayout = new javax.swing.GroupLayout(jpanel_skor_alani);
        jpanel_skor_alani.setLayout(jpanel_skor_alaniLayout);
        jpanel_skor_alaniLayout.setHorizontalGroup(
            jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_skor_alaniLayout.createSequentialGroup()
                .addGroup(jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_skor_alaniLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_oyuncu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_bilgisayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_oyuncu_skor)
                            .addComponent(label_bilgisayar_skor)))
                    .addGroup(jpanel_skor_alaniLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(button_yeni_oyun)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jpanel_skor_alaniLayout.setVerticalGroup(
            jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_skor_alaniLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_oyuncu)
                    .addComponent(label_oyuncu_skor))
                .addGap(18, 18, 18)
                .addGroup(jpanel_skor_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_bilgisayar)
                    .addComponent(label_bilgisayar_skor))
                .addGap(39, 39, 39)
                .addComponent(button_yeni_oyun, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jpanel_oyun_alani.setForeground(new java.awt.Color(153, 255, 102));

        button_oyna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_oyna.setForeground(new java.awt.Color(255, 51, 51));
        button_oyna.setText("Oyna");
        button_oyna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_oynaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Oyuncunun Seçimi:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Bilgisayarın Seçimi");

        combobox_oyuncu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TAŞ", "KAĞIT", "MAKAS" }));
        combobox_oyuncu.setSelectedIndex(-1);
        combobox_oyuncu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_oyuncuİtemStateChanged(evt);
            }
        });

        combobox_bilgisayar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        combobox_bilgisayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        combobox_bilgisayar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_bilgisayarİtemStateChanged(evt);
            }
        });

        jlabel_durum.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jlabel_durum.setForeground(new java.awt.Color(255, 0, 0));
        jlabel_durum.setText("Durum ;");
        jlabel_durum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlabel_kazanan.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jlabel_kazanan.setForeground(new java.awt.Color(255, 51, 0));
        jlabel_kazanan.setText("Bilgisayar kazandı");

        javax.swing.GroupLayout jpanel_oyun_alaniLayout = new javax.swing.GroupLayout(jpanel_oyun_alani);
        jpanel_oyun_alani.setLayout(jpanel_oyun_alaniLayout);
        jpanel_oyun_alaniLayout.setHorizontalGroup(
            jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_oyun_alaniLayout.createSequentialGroup()
                .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_oyun_alaniLayout.createSequentialGroup()
                        .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_oyun_alaniLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(button_resim_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_oyun_alaniLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(combobox_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addComponent(button_oyna, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_resim_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_oyun_alaniLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_oyun_alaniLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlabel_durum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabel_kazanan, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jpanel_oyun_alaniLayout.setVerticalGroup(
            jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_oyun_alaniLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_resim_oyuncu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_resim_bilgisayar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_oyna, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpanel_oyun_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel_durum)
                    .addComponent(jlabel_kazanan, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_kayit_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanel_oyun_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpanel_skor_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanel_kayit_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpanel_oyun_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpanel_skor_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textfield_oyuncu_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_oyuncu_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_oyuncu_adiActionPerformed

    private void button_baslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_baslaActionPerformed
        ad = textfield_oyuncu_adi.getText();
        textfield_oyuncu_adi.setEnabled(false);
        jpanel_kayit_alani.setEnabled(false);
        jpanel_oyun_alani.setVisible(true);
        jpanel_kayit_alani.setVisible(true);
        button_basla.setEnabled(false);
        button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.eray.taskagitmakas.resim/bos.jpg")));
        button_resim_bilgisayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.eray.taskagitmakas.resim/bos.jpg")));

    }//GEN-LAST:event_button_baslaActionPerformed

    private void button_yeni_oyunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_yeni_oyunActionPerformed
        oyuncuskor = 0;
        bilgisayarskor = 0;
        ad = "";
        jpanel_oyun_alani.setVisible(false);
        jpanel_skor_alani.setVisible(false);
        combobox_bilgisayar.setSelectedIndex(-1);
        combobox_oyuncu.setSelectedIndex(-1);
        jpanel_kayit_alani.setEnabled(true);
        textfield_oyuncu_adi.setEnabled(true);
        button_basla.setEnabled(true);

    }//GEN-LAST:event_button_yeni_oyunActionPerformed

    private void button_oynaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_oynaActionPerformed
        bilgisayar = (int)(Math.random()*3);
        combobox_bilgisayar.setSelectedIndex(bilgisayar);
        if(bilgisayar == 0)
        button_resim_bilgisayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/tas.png")));
        else if(bilgisayar == 1)
        button_resim_bilgisayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/kagıt.png")));
        else if(bilgisayar == 2)
        button_resim_bilgisayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/makas.png")));
        kontrol();
    }//GEN-LAST:event_button_oynaActionPerformed

    private void combobox_oyuncuİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_oyuncuİtemStateChanged
        if(String.valueOf(combobox_oyuncu.getSelectedItem()) == "TAŞ")
        button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/tas.png")));
        else if(String.valueOf(combobox_oyuncu.getSelectedItem()) == "KAĞIT")
        button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/kagıt.png")));
        else if(String.valueOf(combobox_oyuncu.getSelectedItem()) == "MAKAS")
        button_resim_oyuncu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resim/makas.png")));
    }//GEN-LAST:event_combobox_oyuncuİtemStateChanged

    private void combobox_bilgisayarİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_bilgisayarİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_bilgisayarİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tas_kagit_makas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tas_kagit_makas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_basla;
    private javax.swing.JButton button_oyna;
    private javax.swing.JButton button_resim_bilgisayar;
    private javax.swing.JButton button_resim_oyuncu;
    private javax.swing.JButton button_yeni_oyun;
    private javax.swing.JComboBox<String> combobox_bilgisayar;
    private javax.swing.JComboBox<String> combobox_oyuncu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlabel_durum;
    private javax.swing.JLabel jlabel_kazanan;
    private javax.swing.JLabel jlabel_oyuncu_adi;
    private javax.swing.JPanel jpanel_kayit_alani;
    private javax.swing.JPanel jpanel_oyun_alani;
    private javax.swing.JPanel jpanel_skor_alani;
    private javax.swing.JLabel label_bilgisayar;
    private javax.swing.JLabel label_bilgisayar_skor;
    private javax.swing.JLabel label_oyuncu;
    private javax.swing.JLabel label_oyuncu_skor;
    private javax.swing.JTextField textfield_oyuncu_adi;
    // End of variables declaration//GEN-END:variables
}
